name: Continuous integration
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.11.0
    - name: Ruby install
      run: devbox install
    - name: Bundle install
      run: devbox run install
    - name: Jekyll build
      run: devbox run build
    - name: Bunny deploy
      uses: ayeressian/bunnycdn-storage-deploy@v2.1.0
      with:
        source: "_site"
        storageZoneName: "${{ secrets.STORAGE_NAME }}"
        storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
        accessKey: "${{ secrets.BUNNY_API_KEY }}"
        pullZoneId: "${{ secrets.ZONE_ID }}"
        upload: "true"
        remove: "true"
        purgePullZone: "true"
